# Web Scraping Lab

You will find in this notebook some scrapy exercises to practise your scraping skills.

**Tips:**

- Check the response status code for each request to ensure you have obtained the intended content.
- Print the response text in each request to understand the kind of info you are getting and its format.
- Check for patterns in the response text to extract the data/info requested in each question.
- Visit the urls below and take a look at their source code through Chrome DevTools. You'll need to identify the html tags, special class names, etc used in the html content you are expected to extract.

**Resources**:
- [Requests library](http://docs.python-requests.org/en/master/#the-user-guide)
- [Beautiful Soup Doc](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Urllib](https://docs.python.org/3/library/urllib.html#module-urllib)
- [re lib](https://docs.python.org/3/library/re.html)
- [lxml lib](https://lxml.de/)
- [Scrapy](https://scrapy.org/)
- [List of HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)
- [HTML basics](http://www.simplehtmlguide.com/cheatsheet.php)
- [CSS basics](https://www.cssbasics.com/#page_start)

#### Below are the libraries and modules you may need. `requests`,  `BeautifulSoup` and `pandas` are already imported for you. If you prefer to use additional libraries feel free to do it.

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

#### Download, parse (using BeautifulSoup), and print the content from the Trending Developers page from GitHub:

In [4]:
# This is the url you will scrape in this exercise
url = 'https://github.com/trending/developers'

In [24]:
html=requests.get(url)

print(html.status_code)

soup = BeautifulSoup(html.content, 'html.parser')

# soup

200

#### Display the names of the trending developers retrieved in the previous step.

Your output should be a Python list of developer names. Each name should not contain any html tag.

**Instructions:**

1. Find out the html tag and class names used for the developer names. You can achieve this using Chrome DevTools.

1. Use BeautifulSoup to extract all the html elements that contain the developer names.

1. Use string manipulation techniques to replace whitespaces and linebreaks (i.e. `\n`) in the *text* of each html element. Use a list to store the clean names.

1. Print the list of names.

Your output should look like below:

```
['trimstray (@trimstray)',
 'joewalnes (JoeWalnes)',
 'charlax (Charles-AxelDein)',
 'ForrestKnight (ForrestKnight)',
 'revery-ui (revery-ui)',
 'alibaba (Alibaba)',
 'Microsoft (Microsoft)',
 'github (GitHub)',
 'facebook (Facebook)',
 'boazsegev (Bo)',
 'google (Google)',
 'cloudfetch',
 'sindresorhus (SindreSorhus)',
 'tensorflow',
 'apache (TheApacheSoftwareFoundation)',
 'DevonCrawford (DevonCrawford)',
 'ARMmbed (ArmMbed)',
 'vuejs (vuejs)',
 'fastai (fast.ai)',
 'QiShaoXuan (Qi)',
 'joelparkerhenderson (JoelParkerHenderson)',
 'torvalds (LinusTorvalds)',
 'CyC2018',
 'komeiji-satori (神楽坂覚々)',
 'script-8']
 ```

In [40]:
table = soup.find_all('h1',{'class': "h3 lh-condensed"})
result=[i.text.replace('\n','').strip() for i in table]

result

['Dries Vints',
 'Ariel Mashraki',
 'Tomas Votruba',
 'Miek Gieben',
 'hiroki',
 'Felix Angelov',
 'Joakim Sørensen',
 'Thomas Lovén',
 'Ron Evans',
 'Samuel Colvin',
 'Daniel Mendler',
 'Julien Le Coupanec',
 'Frost Ming',
 'Jörg Thalheim',
 'Michele Locati',
 'Ross Wightman',
 'Thibault Duplessis',
 'hrsh7th',
 'Matthias',
 'Wei Wang',
 'Henrik Rydgård',
 'Fons van der Plas',
 'Arvid Norberg',
 'pedrobern',
 'Blake Blackshear']

#### Display the trending Python repositories in GitHub.

The steps to solve this problem is similar to the previous one except that you need to find out the repository names instead of developer names.

In [1]:
# This is the url you will scrape in this exercise
url2 = 'https://github.com/trending/python?since=daily'

In [16]:
html2=requests.get(url2)

print(html2.status_code)

soup = BeautifulSoup(html2.content, 'html.parser')

table2 = soup.find_all('h1',{'class': "h3 lh-condensed"})

result2=[i.text.replace('\n','').split('/')[1].strip() for i in table2]

result2

200

['spaCy',
 'budgetml',
 'Python',
 'stylegan2-ada-pytorch',
 'full-stack-fastapi-postgresql',
 'manim',
 'Bug-Bounty-Toolz',
 'system-design-primer',
 'CppCoreGuidelines',
 'red-python-scripts',
 'PayloadsAllTheThings',
 'horovod',
 'pororo',
 'MathInspector',
 'poetry',
 'compose',
 'bad-apple-bot',
 'spack',
 'web-brutator',
 'mmpose',
 'optuna',
 'mlflow',
 'easytrader',
 'revolut-stocks',
 'CenterNet']

#### Display all the image links from Walt Disney wikipedia page.

In [17]:
# This is the url you will scrape in this exercise
url3 = 'https://en.wikipedia.org/wiki/Walt_Disney'

In [50]:
html3=requests.get(url3)

print(html3.status_code)

soup = BeautifulSoup(html3.content, 'html.parser')

table3 = soup.find_all('a',{'class': "image"})

result3=[i.get('href') for i in table3]

print(result3)

200
['/wiki/File:Walt_Disney_1946.JPG', '/wiki/File:Walt_Disney_1942_signature.svg', '/wiki/File:Walt_Disney_envelope_ca._1921.jpg', '/wiki/File:Trolley_Troubles_poster.jpg', '/wiki/File:Walt_Disney_and_his_cartoon_creation_%22Mickey_Mouse%22_-_National_Board_of_Review_Magazine.jpg', '/wiki/File:Steamboat-willie.jpg', '/wiki/File:Walt_Disney_1935.jpg', '/wiki/File:Walt_Disney_Snow_white_1937_trailer_screenshot_(13).jpg', '/wiki/File:Disney_drawing_goofy.jpg', '/wiki/File:DisneySchiphol1951.jpg', '/wiki/File:WaltDisneyplansDisneylandDec1954.jpg', '/wiki/File:Walt_disney_portrait_right.jpg', '/wiki/File:Walt_Disney_Grave.JPG', '/wiki/File:Roy_O._Disney_with_Company_at_Press_Conference.jpg', '/wiki/File:Disney_Display_Case.JPG', '/wiki/File:Disney1968.jpg', '/wiki/File:Animation_disc.svg', '/wiki/File:P_vip.svg', '/wiki/File:Magic_Kingdom_castle.jpg', '/wiki/File:Video-x-generic.svg', '/wiki/File:Flag_of_Los_Angeles_County,_California.svg', '/wiki/File:Blank_television_set.svg', '/wiki/File:Flag_of_the_United_States.svg']

#### Retrieve an arbitary Wikipedia page of "Python" and create a list of links on that page.

In [51]:
# This is the url you will scrape in this exercise
url4 ='https://en.wikipedia.org/wiki/Python'

In [57]:
html4=requests.get(url4)

print(html4.status_code)

soup = BeautifulSoup(html4.content, 'html.parser')

table4 = soup.find_all('a')

result4=[i.get('href') for i in table4]

result4
# url_sub=result4[3]

# html42=requests.get(url_sub)

# print(html42.status_code)

# soup = BeautifulSoup(html42.content, 'html.parser')

# table42 = soup.find_all('a')

# result42=[i.get('href') for i in table42]

# result42

200

[None,
 '#mw-head',
 '#searchInput',
 'https://en.wiktionary.org/wiki/Python',
 'https://en.wiktionary.org/wiki/python',
 '/wiki/Pythons',
 '/wiki/Python_(genus)',
 '#Computing',
 '#People',
 '#Roller_coasters',
 '#Vehicles',
 '#Weaponry',
 '#Other_uses',
 '#See_also',
 '/w/index.php?title=Python&action=edit&section=1',
 '/wiki/Python_(programming_language)',
 '/wiki/CMU_Common_Lisp',
 '/wiki/PERQ#PERQ_3',
 '/w/index.php?title=Python&action=edit&section=2',
 '/wiki/Python_of_Aenus',
 '/wiki/Python_(painter)',
 '/wiki/Python_of_Byzantium',
 '/wiki/Python_of_Catana',
 '/wiki/Python_Anghelo',
 '/w/index.php?title=Python&action=edit&section=3',
 '/wiki/Python_(Efteling)',
 '/wiki/Python_(Busch_Gardens_Tampa_Bay)',
 '/wiki/Python_(Coney_Island,_Cincinnati,_Ohio)',
 '/w/index.php?title=Python&action=edit&section=4',
 '/wiki/Python_(automobile_maker)',
 '/wiki/Python_(Ford_prototype)',
 '/w/index.php?title=Python&action=edit&section=5',
 '/wiki/Python_(missile)',
 '/wiki/Python_(nuclear_primary)',
 '/wiki/Colt_Python',
 '/w/index.php?title=Python&action=edit&section=6',
 '/wiki/PYTHON',
 '/wiki/Python_(film)',
 '/wiki/Python_(mythology)',
 '/wiki/Monty_Python',
 '/wiki/Python_(Monty)_Pictures',
 '/w/index.php?title=Python&action=edit&section=7',
 '/wiki/Cython',
 '/wiki/Pyton',
 '/wiki/Pithon',
 '/wiki/File:Disambig_gray.svg',
 '/wiki/Help:Disambiguation',
 'https://en.wikipedia.org/w/index.php?title=Special:WhatLinksHere/Python&namespace=0',
 'https://en.wikipedia.org/w/index.php?title=Python&oldid=997582414',
 '/wiki/Help:Category',
 '/wiki/Category:Disambiguation_pages',
 '/wiki/Category:Human_name_disambiguation_pages',
 '/wiki/Category:Disambiguation_pages_with_given-name-holder_lists',
 '/wiki/Category:Disambiguation_pages_with_short_descriptions',
 '/wiki/Category:Short_description_is_different_from_Wikidata',
 '/wiki/Category:All_article_disambiguation_pages',
 '/wiki/Category:All_disambiguation_pages',
 '/wiki/Category:Animal_common_name_disambiguation_pages',
 '/wiki/Special:MyTalk',
 '/wiki/Special:MyContributions',
 '/w/index.php?title=Special:CreateAccount&returnto=Python',
 '/w/index.php?title=Special:UserLogin&returnto=Python',
 '/wiki/Python',
 '/wiki/Talk:Python',
 '/wiki/Python',
 '/w/index.php?title=Python&action=edit',
 '/w/index.php?title=Python&action=history',
 '/wiki/Main_Page',
 '/wiki/Main_Page',
 '/wiki/Wikipedia:Contents',
 '/wiki/Portal:Current_events',
 '/wiki/Special:Random',
 '/wiki/Wikipedia:About',
 '//en.wikipedia.org/wiki/Wikipedia:Contact_us',
 'https://donate.wikimedia.org/wiki/Special:FundraiserRedirector?utm_source=donate&utm_medium=sidebar&utm_campaign=C13_en.wikipedia.org&uselang=en',
 '/wiki/Help:Contents',
 '/wiki/Help:Introduction',
 '/wiki/Wikipedia:Community_portal',
 '/wiki/Special:RecentChanges',
 '/wiki/Wikipedia:File_Upload_Wizard',
 '/wiki/Special:WhatLinksHere/Python',
 '/wiki/Special:RecentChangesLinked/Python',
 '/wiki/Wikipedia:File_Upload_Wizard',
 '/wiki/Special:SpecialPages',
 '/w/index.php?title=Python&oldid=997582414',
 '/w/index.php?title=Python&action=info',
 '/w/index.php?title=Special:CiteThisPage&page=Python&id=997582414&wpFormIdentifier=titleform',
 'https://www.wikidata.org/wiki/Special:EntityPage/Q747452',
 '/w/index.php?title=Special:DownloadAsPdf&page=Python&action=show-download-screen',
 '/w/index.php?title=Python&printable=yes',
 'https://commons.wikimedia.org/wiki/Category:Python',
 'https://af.wikipedia.org/wiki/Python',
 'https://als.wikipedia.org/wiki/Python',
 'https://ar.wikipedia.org/wiki/%D8%A8%D8%A7%D9%8A%D8%AB%D9%88%D9%86_(%D8%AA%D9%88%D8%B6%D9%8A%D8%AD)',
 'https://az.wikipedia.org/wiki/Python',
 'https://bn.wikipedia.org/wiki/%E0%A6%AA%E0%A6%BE%E0%A6%87%E0%A6%A5%E0%A6%A8_(%E0%A6%A6%E0%A7%8D%E0%A6%AC%E0%A7%8D%E0%A6%AF%E0%A6%B0%E0%A7%8D%E0%A6%A5%E0%A6%A4%E0%A6%BE_%E0%A6%A8%E0%A6%BF%E0%A6%B0%E0%A6%B8%E0%A6%A8)',
 'https://be.wikipedia.org/wiki/Python',
 'https://bg.wikipedia.org/wiki/%D0%9F%D0%B8%D1%82%D0%BE%D0%BD_(%D0%BF%D0%BE%D1%8F%D1%81%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5)',
 'https://cs.wikipedia.org/wiki/Python_(rozcestn%C3%ADk)',
 'https://da.wikipedia.org/wiki/Python',
 'https://de.wikipedia.org/wiki/Python',
 'https://eo.wikipedia.org/wiki/Pitono_(apartigilo)',
 'https://eu.wikipedia.org/wiki/Python_(argipena)',
 'https://fa.wikipedia.org/wiki/%D9%BE%D8%A7%DB%8C%D8%AA%D9%88%D9%86',
 'https://fr.wikipedia.org/wiki/Python',
 'https://ko.wikipedia.org/wiki/%ED%8C%8C%EC%9D%B4%EC%84%A0',
 'https://hr.wikipedia.org/wiki/Python_(razdvojba)',
 'https://io.wikipedia.org/wiki/Pitono',
 'https://id.wikipedia.org/wiki/Python',
 'https://ia.wikipedia.org/wiki/Python_(disambiguation)',
 'https://is.wikipedia.org/wiki/Python_(a%C3%B0greining)',
 'https://it.wikipedia.org/wiki/Python_(disambigua)',
 'https://he.wikipedia.org/wiki/%D7%A4%D7%99%D7%AA%D7%95%D7%9F',
 'https://ka.wikipedia.org/wiki/%E1%83%9E%E1%83%98%E1%83%97%E1%83%9D%E1%83%9C%E1%83%98_(%E1%83%9B%E1%83%A0%E1%83%90%E1%83%95%E1%83%90%E1%83%9A%E1%83%9B%E1%83%9C%E1%83%98%E1%83%A8%E1%83%95%E1%83%9C%E1%83%94%E1%83%9A%E1%83%9D%E1%83%95%E1%83%90%E1%83%9C%E1%83%98)',
 'https://kg.wikipedia.org/wiki/Mboma_(nyoka)',
 'https://la.wikipedia.org/wiki/Python_(discretiva)',
 'https://lb.wikipedia.org/wiki/Python',
 'https://hu.wikipedia.org/wiki/Python_(egy%C3%A9rtelm%C5%B1s%C3%ADt%C5%91_lap)',
 'https://mr.wikipedia.org/wiki/%E0%A4%AA%E0%A4%BE%E0%A4%AF%E0%A4%A5%E0%A5%89%E0%A4%A8_(%E0%A4%86%E0%A4%9C%E0%A5%8D%E0%A4%9E%E0%A4%BE%E0%A4%B5%E0%A4%B2%E0%A5%80_%E0%A4%AD%E0%A4%BE%E0%A4%B7%E0%A4%BE)',
 'https://nl.wikipedia.org/wiki/Python',
 'https://ja.wikipedia.org/wiki/%E3%83%91%E3%82%A4%E3%82%BD%E3%83%B3',
 'https://no.wikipedia.org/wiki/Pyton',
 'https://pl.wikipedia.org/wiki/Pyton',
 'https://pt.wikipedia.org/wiki/Python_(desambigua%C3%A7%C3%A3o)',
 'https://ru.wikipedia.org/wiki/Python_(%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F)',
 'https://sk.wikipedia.org/wiki/Python',
 'https://sr.wikipedia.org/wiki/%D0%9F%D0%B8%D1%82%D0%BE%D0%BD_(%D0%B2%D0%B8%D1%88%D0%B5%D0%B7%D0%BD%D0%B0%D1%87%D0%BD%D0%B0_%D0%BE%D0%B4%D1%80%D0%B5%D0%B4%D0%BD%D0%B8%D1%86%D0%B0)',
 'https://sh.wikipedia.org/wiki/Python',
 'https://fi.wikipedia.org/wiki/Python',
 'https://sv.wikipedia.org/wiki/Pyton',
 'https://th.wikipedia.org/wiki/%E0%B9%84%E0%B8%9E%E0%B8%97%E0%B8%AD%E0%B8%99',
 'https://tr.wikipedia.org/wiki/Python',
 'https://uk.wikipedia.org/wiki/%D0%9F%D1%96%D1%84%D0%BE%D0%BD',
 'https://ur.wikipedia.org/wiki/%D9%BE%D8%A7%D8%A6%DB%8C%D8%AA%DA%BE%D9%88%D9%86',
 'https://vi.wikipedia.org/wiki/Python',
 'https://zh.wikipedia.org/wiki/Python_(%E6%B6%88%E6%AD%A7%E4%B9%89)',
 'https://www.wikidata.org/wiki/Special:EntityPage/Q747452#sitelinks-wikipedia',
 '//en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License',
 '//creativecommons.org/licenses/by-sa/3.0/',
 '//foundation.wikimedia.org/wiki/Terms_of_Use',
 '//foundation.wikimedia.org/wiki/Privacy_policy',
 '//www.wikimediafoundation.org/',
 'https://foundation.wikimedia.org/wiki/Privacy_policy',
 '/wiki/Wikipedia:About',
 '/wiki/Wikipedia:General_disclaimer',
 '//en.wikipedia.org/wiki/Wikipedia:Contact_us',
 '//en.m.wikipedia.org/w/index.php?title=Python&mobileaction=toggle_view_mobile',
 'https://www.mediawiki.org/wiki/Special:MyLanguage/How_to_contribute',
 'https://stats.wikimedia.org/#/en.wikipedia.org',
 'https://foundation.wikimedia.org/wiki/Cookie_statement',
 'https://wikimediafoundation.org/',
 'https://www.mediawiki.org/']

#### Find the number of titles that have changed in the United States Code since its last release point.

In [58]:
# This is the url you will scrape in this exercise
url5 = 'http://uscode.house.gov/download/download.shtml'

In [61]:
html5=requests.get(url5)

print(html5.status_code)

soup = BeautifulSoup(html5.content, 'html.parser')

table5 = soup.find_all('div',{'class':'usctitlechanged'})

result5=[i.text.replace('\n','').strip() for i in table5]

result5

200

['Title 6 - Domestic Security',
 'Title 10 - Armed Forces ٭',
 'Title 15 - Commerce and Trade',
 'Title 20 - Education',
 'Title 28 - Judiciary and Judicial Procedure ٭',
 'Title 31 - Money and Finance ٭',
 'Title 33 - Navigation and Navigable Waters',
 'Title 36 - Patriotic and National Observances, Ceremonies, and Organizations ٭',
 'Title 37 - Pay and Allowances of the Uniformed Services ٭',
 "Title 38 - Veterans' Benefits ٭",
 'Title 40 - Public Buildings, Property, and Works ٭',
 'Title 46 - Shipping ٭']

#### Find a Python list with the top ten FBI's Most Wanted names.

In [62]:
# This is the url you will scrape in this exercise
url6 = 'https://www.fbi.gov/wanted/topten'

In [63]:
html6=requests.get(url6)

print(html6.status_code)

soup = BeautifulSoup(html6.content, 'html.parser')

table6 = soup.find_all('h3',{'class':'title'})

result6=[i.text.replace('\n','').strip() for i in table6]

result6

200

['ALEJANDRO ROSALES CASTILLO',
 'ARNOLDO JIMENEZ',
 'JASON DEREK BROWN',
 'ALEXIS FLORES',
 'JOSE RODOLFO VILLARREAL-HERNANDEZ',
 'EUGENE PALMER',
 'RAFAEL CARO-QUINTERO',
 'ROBERT WILLIAM FISHER',
 'BHADRESHKUMAR CHETANBHAI PATEL',
 'YASER ABDEL SAID']

####  Display the 20 latest earthquakes info (date, time, latitude, longitude and region name) by the EMSC as a pandas dataframe.

In [2]:
# This is the url you will scrape in this exercise
url7 = 'https://www.emsc-csem.org/Earthquake/'

In [32]:
html7=requests.get(url7)

print(html7.status_code)

soup = BeautifulSoup(html7.content, 'html.parser')

tbody = soup.find('tbody')
trs = tbody.find_all('tr')

res = []
for tr in trs:
    td = tr.find_all('td')
    row = [cell.text.strip() for cell in tr if cell.text]
    if row:
        res.append(row)

res

200

[['earthquake2021-02-05\xa0\xa0\xa018:25:11.119min ago',
  '37.22',
  'N',
  '3.70',
  'W',
  '3',
  'ML',
  '1.7',
  'SPAIN',
  '2021-02-05 18:37'],
 ['earthquake2021-02-05\xa0\xa0\xa018:24:47.019min ago',
  '38.95',
  'N',
  '26.07',
  'E',
  '15',
  'ML',
  '2.4',
  'NEAR THE COAST OF WESTERN TURKEY',
  '2021-02-05 18:34'],
 ['earthquake2021-02-05\xa0\xa0\xa018:14:07.030min ago',
  '36.29',
  'N',
  '97.51',
  'W',
  '2',
  'ML',
  '2.4',
  'OKLAHOMA',
  '2021-02-05 18:18'],
 ['earthquake2021-02-05\xa0\xa0\xa018:04:00.140min ago',
  '19.22',
  'N',
  '155.42',
  'W',
  '36',
  'ML',
  '2.4',
  'ISLAND OF HAWAII, HAWAII',
  '2021-02-05 18:09'],
 ['F',
  'earthquake2021-02-05\xa0\xa0\xa018:03:21.841min ago',
  '36.29',
  'N',
  '97.52',
  'W',
  '5',
  'ML',
  '2.2',
  'OKLAHOMA',
  '2021-02-05 18:39'],
 ['earthquake2021-02-05\xa0\xa0\xa017:59:13.845min ago',
  '36.29',
  'N',
  '97.52',
  'W',
  '5',
  'ML',
  '2.6',
  'OKLAHOMA',
  '2021-02-05 18:33'],
 ['earthquake2021-02-05\xa0\xa0\xa017:49:26.355min ago',
  '19.15',
  'N',
  '155.46',
  'W',
  '34',
  'Md',
  '2.9',
  'ISLAND OF HAWAII, HAWAII',
  '2021-02-05 17:52'],
 ['IV',
  'earthquake2021-02-05\xa0\xa0\xa017:48:45.355min ago',
  '36.29',
  'N',
  '97.51',
  'W',
  '5',
  'Mw',
  '4.2',
  'OKLAHOMA',
  '2021-02-05 18:30'],
 ['earthquake2021-02-05\xa0\xa0\xa017:45:21.159min ago',
  '28.13',
  'N',
  '15.79',
  'W',
  '20',
  'ML',
  '1.7',
  'CANARY ISLANDS, SPAIN REGION',
  '2021-02-05 18:02'],
 ['earthquake2021-02-05\xa0\xa0\xa017:42:40.01hr 02min ago',
  '2.14',
  'S',
  '120.64',
  'E',
  '10',
  'M',
  '3.0',
  'SULAWESI, INDONESIA',
  '2021-02-05 17:55'],
 ['earthquake2021-02-05\xa0\xa0\xa017:29:35.11hr 15min ago',
  '36.29',
  'N',
  '97.51',
  'W',
  '5',
  'ML',
  '2.6',
  'OKLAHOMA',
  '2021-02-05 17:48'],
 ['earthquake2021-02-05\xa0\xa0\xa017:27:41.41hr 17min ago',
  '36.29',
  'N',
  '97.52',
  'W',
  '7',
  'ML',
  '2.2',
  'OKLAHOMA',
  '2021-02-05 17:39'],
 ['earthquake2021-02-05\xa0\xa0\xa017:25:52.01hr 18min ago',
  '5.67',
  'N',
  '125.57',
  'E',
  '197',
  'M',
  '3.1',
  'MINDANAO, PHILIPPINES',
  '2021-02-05 17:40'],
 ['earthquake2021-02-05\xa0\xa0\xa017:24:41.81hr 20min ago',
  '19.20',
  'N',
  '155.42',
  'W',
  '35',
  'Ml',
  '2.7',
  'ISLAND OF HAWAII, HAWAII',
  '2021-02-05 17:30'],
 ['earthquake2021-02-05\xa0\xa0\xa017:22:13.31hr 22min ago',
  '37.83',
  'N',
  '26.99',
  'E',
  '7',
  'ML',
  '2.0',
  'DODECANESE ISLANDS, GREECE',
  '2021-02-05 17:30'],
 ['earthquake2021-02-05\xa0\xa0\xa017:05:17.71hr 39min ago',
  '36.43',
  'N',
  '28.73',
  'E',
  '7',
  'ML',
  '2.2',
  'DODECANESE IS.-TURKEY BORDER REG',
  '2021-02-05 17:16'],
 ['F',
  'earthquake2021-02-05\xa0\xa0\xa017:01:48.11hr 42min ago',
  '39.22',
  'N',
  '122.99',
  'W',
  '4',
  'Md',
  '2.2',
  'NORTHERN CALIFORNIA',
  '2021-02-05 17:49'],
 ['earthquake2021-02-05\xa0\xa0\xa016:56:38.91hr 48min ago',
  '37.21',
  'N',
  '3.72',
  'W',
  '5',
  'ML',
  '1.6',
  'SPAIN',
  '2021-02-05 17:10'],
 ['earthquake2021-02-05\xa0\xa0\xa016:54:47.01hr 49min ago',
  '37.19',
  'N',
  '3.75',
  'W',
  '10',
  'ML',
  '1.9',
  'SPAIN',
  '2021-02-05 17:06'],
 ['earthquake2021-02-05\xa0\xa0\xa016:46:56.01hr 57min ago',
  '1.53',
  'S',
  '99.23',
  'E',
  '11',
  'M',
  '2.6',
  'KEP. MENTAWAI REGION, INDONESIA',
  '2021-02-05 16:50'],
 ['earthquake2021-02-05\xa0\xa0\xa016:18:43.32hr 25min ago',
  '37.20',
  'N',
  '3.70',
  'W',
  '5',
  'ML',
  '1.5',
  'SPAIN',
  '2021-02-05 16:38'],
 ['earthquake2021-02-05\xa0\xa0\xa016:17:37.12hr 27min ago',
  '36.29',
  'N',
  '97.52',
  'W',
  '5',
  'ML',
  '3.4',
  'OKLAHOMA',
  '2021-02-05 17:04'],
 ['earthquake2021-02-05\xa0\xa0\xa016:09:41.02hr 35min ago',
  '3.51',
  'S',
  '81.03',
  'W',
  '56',
  'M',
  '3.8',
  'NEAR COAST OF NORTHERN PERU',
  '2021-02-05 16:15'],
 ['earthquake2021-02-05\xa0\xa0\xa016:05:04.72hr 39min ago',
  '37.35',
  'N',
  '3.66',
  'W',
  '10',
  'ML',
  '2.3',
  'SPAIN',
  '2021-02-05 16:17'],
 ['F',
  'earthquake2021-02-05\xa0\xa0\xa015:48:13.72hr 56min ago',
  '40.50',
  'N',
  '45.29',
  'E',
  '2',
  'ML',
  '4.2',
  'ARMENIA',
  '2021-02-05 18:16'],
 ['F',
  'earthquake2021-02-05\xa0\xa0\xa015:44:24.83hr 00min ago',
  '40.51',
  'N',
  '45.33',
  'E',
  '1',
  'ML',
  '3.8',
  'ARMENIA',
  '2021-02-05 17:35'],
 ['earthquake2021-02-05\xa0\xa0\xa015:41:37.13hr 03min ago',
  '22.76',
  'S',
  '171.67',
  'E',
  '30',
  'Mw',
  '5.3',
  'SOUTHEAST OF LOYALTY ISLANDS',
  '2021-02-05 18:31'],
 ['earthquake2021-02-05\xa0\xa0\xa015:36:42.13hr 07min ago',
  '38.44',
  'N',
  '31.79',
  'E',
  '7',
  'ML',
  '2.4',
  'WESTERN TURKEY',
  '2021-02-05 15:49'],
 ['49',
  'IV',
  'earthquake2021-02-05\xa0\xa0\xa015:36:09.93hr 08min ago',
  '40.51',
  'N',
  '45.41',
  'E',
  '10',
  'Mw',
  '5.1',
  'ARMENIA',
  '2021-02-05 16:20'],
 ['earthquake2021-02-05\xa0\xa0\xa015:21:08.03hr 23min ago',
  '4.69',
  'S',
  '133.95',
  'E',
  '10',
  'M',
  '4.2',
  'NEAR S COAST OF PAPUA, INDONESIA',
  '2021-02-05 15:50'],
 ['earthquake2021-02-05\xa0\xa0\xa015:20:40.93hr 24min ago',
  '65.10',
  'N',
  '152.12',
  'W',
  '10',
  'ML',
  '2.6',
  'NORTHERN ALASKA',
  '2021-02-05 17:26'],
 ['earthquake2021-02-05\xa0\xa0\xa015:17:24.03hr 27min ago',
  '1.72',
  'N',
  '99.24',
  'E',
  '10',
  'M',
  '2.9',
  'NORTHERN SUMATRA, INDONESIA',
  '2021-02-05 15:25'],
 ['earthquake2021-02-05\xa0\xa0\xa015:15:17.33hr 29min ago',
  '42.09',
  'N',
  '8.15',
  'W',
  '19',
  'ML',
  '1.6',
  'SPAIN',
  '2021-02-05 15:38'],
 ['earthquake2021-02-05\xa0\xa0\xa015:11:07.03hr 33min ago',
  '1.77',
  'N',
  '99.19',
  'E',
  '10',
  'M',
  '2.7',
  'NORTHERN SUMATRA, INDONESIA',
  '2021-02-05 15:15'],
 ['earthquake2021-02-05\xa0\xa0\xa014:57:50.23hr 46min ago',
  '47.76',
  'N',
  '8.83',
  'E',
  '5',
  'ML',
  '1.5',
  'GERMANY',
  '2021-02-05 15:04'],
 ['earthquake2021-02-05\xa0\xa0\xa014:57:04.53hr 47min ago',
  '19.21',
  'N',
  '155.42',
  'W',
  '36',
  'Md',
  '2.3',
  'ISLAND OF HAWAII, HAWAII',
  '2021-02-05 15:00'],
 ['earthquake2021-02-05\xa0\xa0\xa014:54:45.03hr 49min ago',
  '20.67',
  'S',
  '68.92',
  'W',
  '113',
  'ML',
  '2.8',
  'TARAPACA, CHILE',
  '2021-02-05 18:32'],
 ['earthquake2021-02-05\xa0\xa0\xa014:50:35.33hr 54min ago',
  '47.75',
  'N',
  '8.83',
  'E',
  '9',
  'ML',
  '1.5',
  'GERMANY',
  '2021-02-05 14:56'],
 ['earthquake2021-02-05\xa0\xa0\xa014:46:25.13hr 58min ago',
  '47.75',
  'N',
  '8.83',
  'E',
  '10',
  'ML',
  '1.6',
  'GERMANY',
  '2021-02-05 16:58'],
 ['earthquake2021-02-05\xa0\xa0\xa014:39:10.54hr 05min ago',
  '37.75',
  'N',
  '15.00',
  'E',
  '1',
  'ML',
  '2.2',
  'SICILY, ITALY',
  '2021-02-05 14:43'],
 ['earthquake2021-02-05\xa0\xa0\xa014:31:14.04hr 13min ago',
  '9.97',
  'S',
  '117.80',
  'E',
  '10',
  'M',
  '4.3',
  'SUMBAWA REGION, INDONESIA',
  '2021-02-05 14:40'],
 ['earthquake2021-02-05\xa0\xa0\xa014:28:34.64hr 16min ago',
  '47.76',
  'N',
  '8.82',
  'E',
  '10',
  'ML',
  '2.1',
  'GERMANY',
  '2021-02-05 16:41'],
 ['earthquake2021-02-05\xa0\xa0\xa014:21:44.34hr 22min ago',
  '47.75',
  'N',
  '8.83',
  'E',
  '9',
  'ML',
  '1.2',
  'GERMANY',
  '2021-02-05 14:27'],
 ['earthquake2021-02-05\xa0\xa0\xa014:19:43.84hr 24min ago',
  '47.75',
  'N',
  '8.83',
  'E',
  '9',
  'ML',
  '1.5',
  'GERMANY',
  '2021-02-05 14:27'],
 ['earthquake2021-02-05\xa0\xa0\xa014:15:02.04hr 29min ago',
  '31.74',
  'S',
  '71.87',
  'W',
  '30',
  'ML',
  '2.6',
  'OFFSHORE COQUIMBO, CHILE',
  '2021-02-05 14:24'],
 ['2',
  'III',
  'earthquake2021-02-05\xa0\xa0\xa014:14:12.04hr 30min ago',
  '47.75',
  'N',
  '8.83',
  'E',
  '10',
  'ML',
  '3.2',
  'GERMANY',
  '2021-02-05 15:18'],
 ['earthquake2021-02-05\xa0\xa0\xa014:08:41.04hr 36min ago',
  '44.31',
  'N',
  '115.19',
  'W',
  '9',
  'Ml',
  '2.0',
  'SOUTHERN IDAHO',
  '2021-02-05 15:35'],
 ['earthquake2021-02-05\xa0\xa0\xa013:58:37.34hr 46min ago',
  '47.76',
  'N',
  '8.83',
  'E',
  '10',
  'ML',
  '2.0',
  'GERMANY',
  '2021-02-05 17:55'],
 ['earthquake2021-02-05\xa0\xa0\xa013:56:50.04hr 47min ago',
  '47.75',
  'N',
  '8.83',
  'E',
  '10',
  'ML',
  '1.9',
  'GERMANY',
  '2021-02-05 18:28'],
 ['earthquake2021-02-05\xa0\xa0\xa013:49:00.04hr 55min ago',
  '42.19',
  'N',
  '18.76',
  'E',
  '8',
  'ML',
  '2.0',
  'ADRIATIC SEA',
  '2021-02-05 14:12']]

In [33]:
#cleaning values
for row in res[:20]:
    if 'earthquake' not in row[0]:
        row.pop(0)

In [35]:
colnames=['Time','Latitude','Orientation Lat', 'Longitude','Orientation Lon','Depth', 'Magnitude','Type','Region','Finishing time' ]
df=pd.DataFrame(res[:20], columns=colnames)
df

,Time,Latitude,Orientation Lat,Longitude,Orientation Lon,Depth,Magnitude,Type,Region,Finishing time
0,earthquake2021-02-05 18:25:11.119min ago,37.22,N,3.70,W,3,ML,1.7,SPAIN,2021-02-05 18:37
1,earthquake2021-02-05 18:24:47.019min ago,38.95,N,26.07,E,15,ML,2.4,NEAR THE COAST OF WESTERN TURKEY,2021-02-05 18:34
2,earthquake2021-02-05 18:14:07.030min ago,36.29,N,97.51,W,2,ML,2.4,OKLAHOMA,2021-02-05 18:18
3,earthquake2021-02-05 18:04:00.140min ago,19.22,N,155.42,W,36,ML,2.4,"ISLAND OF HAWAII, HAWAII",2021-02-05 18:09
4,earthquake2021-02-05 18:03:21.841min ago,36.29,N,97.52,W,5,ML,2.2,OKLAHOMA,2021-02-05 18:39
5,earthquake2021-02-05 17:59:13.845min ago,36.29,N,97.52,W,5,ML,2.6,OKLAHOMA,2021-02-05 18:33
6,earthquake2021-02-05 17:49:26.355min ago,19.15,N,155.46,W,34,Md,2.9,"ISLAND OF HAWAII, HAWAII",2021-02-05 17:52
7,earthquake2021-02-05 17:48:45.355min ago,36.29,N,97.51,W,5,Mw,4.2,OKLAHOMA,2021-02-05 18:30
8,earthquake2021-02-05 17:45:21.159min ago,28.13,N,15.79,W,20,ML,1.7,"CANARY ISLANDS, SPAIN REGION",2021-02-05 18:02
9,earthquake2021-02-05 17:42:40.01hr 02min ago,2.14,S,120.64,E,10,M,3.0,"SULAWESI, INDONESIA",2021-02-05 17:55
10,earthquake2021-02-05 17:29:35.11hr 15min ago,36.29,N,97.51,W,5,ML,2.6,OKLAHOMA,2021-02-05 17:48
11,earthquake2021-02-05 17:27:41.41hr 17min ago,36.29,N,97.52,W,7,ML,2.2,OKLAHOMA,2021-02-05 17:39
12,earthquake2021-02-05 17:25:52.01hr 18min ago,5.67,N,125.57,E,197,M,3.1,"MINDANAO, PHILIPPINES",2021-02-05 17:40
13,earthquake2021-02-05 17:24:41.81hr 20min ago,19.20,N,155.42,W,35,Ml,2.7,"ISLAND OF HAWAII, HAWAII",2021-02-05 17:30
14,earthquake2021-02-05 17:22:13.31hr 22min ago,37.83,N,26.99,E,7,ML,2.0,"DODECANESE ISLANDS, GREECE",2021-02-05 17:30
15,earthquake2021-02-05 17:05:17.71hr 39min ago,36.43,N,28.73,E,7,ML,2.2,DODECANESE IS.-TURKEY BORDER REG,2021-02-05 17:16
16,earthquake2021-02-05 17:01:48.11hr 42min ago,39.22,N,122.99,W,4,Md,2.2,NORTHERN CALIFORNIA,2021-02-05 17:49
17,earthquake2021-02-05 16:56:38.91hr 48min ago,37.21,N,3.72,W,5,ML,1.6,SPAIN,2021-02-05 17:10
18,earthquake2021-02-05 16:54:47.01hr 49min ago,37.19,N,3.75,W,10,ML,1.9,SPAIN,2021-02-05 17:06
19,earthquake2021-02-05 16:46:56.01hr 57min ago,1.53,S,99.23,E,11,M,2.6,"KEP. MENTAWAI REGION, INDONESIA",2021-02-05 16:50

#### Count the number of tweets by a given Twitter account.
Ask the user for the handle (@handle) of a twitter account. You will need to include a ***try/except block*** for account names not found. 
<br>***Hint:*** the program should count the number of tweets for any provided account.

In [ ]:
# This is the url you will scrape in this exercise 
# You will need to add the account credentials to this url
url = 'https://twitter.com/'

In [ ]:
# your code here

#### Number of followers of a given twitter account
Ask the user for the handle (@handle) of a twitter account. You will need to include a ***try/except block*** for account names not found. 
<br>***Hint:*** the program should count the followers for any provided account.

In [ ]:
# This is the url you will scrape in this exercise 
# You will need to add the account credentials to this url
url8 = 'https://twitter.com/'

In [ ]:
# your code here

#### List all language names and number of related articles in the order they appear in wikipedia.org.

In [36]:
# This is the url you will scrape in this exercise
url9 = 'https://www.wikipedia.org/'

In [76]:
html9=requests.get(url9)

print(html9.status_code)

soup = BeautifulSoup(html9.content, 'html.parser')

cells = soup.find_all('a',{'class': 'link-box'})

import re

dict={}
for item in cells:
    lang=item.find('strong').text
    articles=item.find('bdi').text
    article=articles.replace('\xa0','.').replace('+', ' articles')
    dict[lang]=article

dict

200

{'English': '6.240.000 articles',
 '日本語': '1.251.000 articles',
 'Deutsch': '2.531.000 articles',
 'Español': '1.657.000 articles',
 'Русский': '1.695.000 articles',
 'Français': '2.294.000 articles',
 'Italiano': '1.671.000 articles',
 '中文': '1.174.000 articles',
 'Polski': '1.453.000 articles',
 'Português': '1.054.000 articles'}

#### A list with the different kind of datasets available in data.gov.uk.

In [3]:
# This is the url you will scrape in this exercise
url10 = 'https://data.gov.uk/'

In [6]:
html10=requests.get(url10)

print(html10.status_code)

soup = BeautifulSoup(html10.content, 'html.parser')

table = soup.find('ul',{'class':'govuk-list dgu-topics__list'})

datasets = table.find_all('a',{'class': 'govuk-link'})

datasets_text=[i.text for i in datasets]

datasets_text

200

['Business and economy',
 'Crime and justice',
 'Defence',
 'Education',
 'Environment',
 'Government',
 'Government spending',
 'Health',
 'Mapping',
 'Society',
 'Towns and cities',
 'Transport']

#### Display the top 10 languages by number of native speakers stored in a pandas dataframe.

In [7]:
# This is the url you will scrape in this exercise
url11 = 'https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers'

In [64]:
html11=requests.get(url11)

print(html11.status_code)

soup = BeautifulSoup(html11.content, 'html.parser')

table = soup.find('table',{'class':'wikitable sortable'})

colnames=[]
ths = table.find_all('th')
for th in ths:
    colnames.append(th.text.strip())


res = []
trs = table.find_all('tr')
for tr in trs:
    td = tr.find_all('td')
    row = [cell.text.strip() for cell in td if cell.text]
    if row:
        res.append(row)

df=pd.DataFrame(res[:10], columns=colnames).set_index('Rank')
df

200

,Language,Speakers(millions),Percentageof world pop.(March 2019)[8],Language family,Branch
Rank,,,,,
1,Mandarin Chinese,918,11.922%,Sino-Tibetan,Sinitic
2,Spanish,480,5.994%,Indo-European,Romance
3,English,379,4.922%,Indo-European,Germanic
4,Hindi (sanskritised Hindustani)[9],341,4.429%,Indo-European,Indo-Aryan
5,Bengali,228,2.961%,Indo-European,Indo-Aryan
6,Portuguese,221,2.870%,Indo-European,Romance
7,Russian,154,2.000%,Indo-European,Balto-Slavic
8,Japanese,128,1.662%,Japonic,Japanese
9,Western Punjabi[10],92.7,1.204%,Indo-European,Indo-Aryan
10,Marathi,83.1,1.079%,Indo-European,Indo-Aryan

## Bonus
#### Scrape a certain number of tweets of a given Twitter account.

In [ ]:
# This is the url you will scrape in this exercise 
# You will need to add the account credentials to this url
urlb1 = 'https://twitter.com/'

In [ ]:
# your code here

#### Display IMDB's top 250 data (movie name, initial release, director name and stars) as a pandas dataframe.

In [19]:
# This is the url you will scrape in this exercise 
urlb2 = 'https://www.imdb.com/chart/top'

In [33]:
htmlb2=requests.get(urlb2)

print(htmlb4.status_code)

soup = BeautifulSoup(htmlb2.content, 'html.parser')

tds = soup.find_all('td',{'class':'titleColumn'})
titles=[]
years=[]
directors=[]
for td in tds:
    a_element=td.find('a')
    titles.append(a_element.text)
    directors.append(a_element.get('title').split('(dir.)')[0])
    years.append(td.find('span',{'class':'secondaryInfo'}).text)

title_list=[title.replace('\n','') for title in titles]
# print(title_list)
# print(directors)
# print(years)
                 
ratings = soup.find_all('td',{'class':'ratingColumn imdbRating'})

   
rating_list=[rating.text.replace('\n','').strip() for rating in ratings if rating.text]


# print(rating_list)

dict={'Rank':list(range(1,251)),'Titles':title_list,
      'Year of release':years, 'Director':directors,
      'Rating':rating_list}
df=pd.DataFrame(dict).set_index('Rank')

df

200

,Titles,Year of release,Director,Rating
Rank,,,,
1,Cadena perpetua,(1994),Frank Darabont,9.2
2,El padrino,(1972),Francis Ford Coppola,9.1
3,El padrino: Parte II,(1974),Francis Ford Coppola,9.0
4,El caballero oscuro,(2008),Christopher Nolan,9.0
5,12 hombres sin piedad,(1957),Sidney Lumet,8.9
...,...,...,...,...
246,La batalla de Argel,(1966),Gillo Pontecorvo,8.0
247,Mandarinas,(2013),Zaza Urushadze,8.0
248,Criadas y señoras,(2011),Tate Taylor,8.0
249,Neon Genesis Evangelion: The End of Evangelion,(1997),Hideaki Anno,8.0
250,Tres colores: Rojo,(1994),Krzysztof Kieslowski,8.0

#### Display the movie name, year and a brief summary of the top 10 random movies (IMDB) as a pandas dataframe.

In [ ]:
#This is the url you will scrape in this exercise
urlb2 = 'http://www.imdb.com/chart/top'

In [47]:
htmlb2=requests.get(urlb2)

print(htmlb4.status_code)

soup = BeautifulSoup(htmlb2.content, 'html.parser')

tds = soup.find_all('td',{'class':'titleColumn'})

import numpy as np
top10random=np.random.rand(10)
titles=[]
years=[]
summary=[]

for i in top10random:
    a_element=tds[int(i*250)].find('a')
    titles.append(a_element.text)
    years.append(td.find('span',{'class':'secondaryInfo'}).text)
    
    link=a_element.get('href')
    sub_html=requests.get('https://www.imdb.com'+link)
    sub_soup=BeautifulSoup(sub_html.content, 'html.parser')
#     print(sub_soup)
    plot=sub_soup.find('div',{'class':'summary_text'})
    summary.append(plot.text)

title_list=[title.replace('\n','') for title in titles]
# print(title_list)
# print(years)
summary_clean=[x.replace('\n','').strip() for x in summary]
print(summary_clean)

dict={'Titles':title_list,'Year of release':years,
      'Summary': summary_clean}
df=pd.DataFrame(dict)

df

200
["A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.", 'A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.', 'An in-depth examination of the ways in which the U.S. Vietnam War impacts and disrupts the lives of people in a small industrial town in Pennsylvania.', 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.', 'Desperate measures are taken by a man who tries to save his family from the dark side of the law, after they commit an unexpected crime.', 'Held captive for 7 years in an enclosed space, a woman and her young son finally gain their freedom, allowing the boy to experience the outside world for the first time.', 'A clash between Sultan and Shahid Khan leads to the expulsion of Khan from Wasseypur, and ignites a deadly blood feud spanning three generations.', "An organized crime dynasty's aging patriarch transfers control of his clandestine empire to his reluctant son.", 'Renton, deeply immersed in the Edinburgh drug scene, tries to clean up and get out, despite the allure of the drugs and influence of friends.', 'The life of boxer Jake LaMotta, whose violence and temper that led him to the top in the ring destroyed his life outside of it.']

,Titles,Year of release,Summary
0,Jurassic Park (Parque Jurásico),(1994),A pragmatic paleontologist visiting an almost ...
1,Los siete samuráis,(1994),A poor village under attack by bandits recruit...
2,El cazador,(1994),An in-depth examination of the ways in which t...
3,Django desencadenado,(1994),"With the help of a German bounty hunter, a fre..."
4,Drishyam,(1994),Desperate measures are taken by a man who trie...
5,La habitación,(1994),"Held captive for 7 years in an enclosed space,..."
6,Gangs of Wasseypur,(1994),A clash between Sultan and Shahid Khan leads t...
7,El padrino,(1994),An organized crime dynasty's aging patriarch t...
8,Trainspotting,(1994),"Renton, deeply immersed in the Edinburgh drug ..."
9,Toro salvaje,(1994),"The life of boxer Jake LaMotta, whose violence..."

#### Find the live weather report (temperature, wind speed, description and weather) of a given city.

In [48]:
#https://openweathermap.org/current
city = input('Enter the city: ')
urlb3 = 'http://api.openweathermap.org/data/2.5/weather?'+'q='+city+'&APPID=b35975e18dc93725acb092f7272cc6b8&units=metric'

Enter the city:  London

In [51]:
res=requests.get(urlb3)
data=res.json()

temperature=data['main']['temp']
wind_speed=data['wind']['speed']
description=data['weather'][0]['description']
weather=data['weather'][0]['main']

print(f'The weather in {city} is {description}, with a temperature of {temperature} degrees and a wind speed of {wind_speed} m/s')

The weather in London is light rain, with a temperature of 4.8 degrees and a wind speed of 3.09 m/s

#### Find the book name, price and stock availability as a pandas dataframe.

In [1]:
# This is the url you will scrape in this exercise. 
# It is a fictional bookstore created to be scraped. 
urlb4 = 'http://books.toscrape.com/'

In [18]:
htmlb4=requests.get(urlb4)

print(htmlb4.status_code)

soup = BeautifulSoup(htmlb4.content, 'html.parser')

titles = soup.find_all('h3')
prices = soup.find_all('p',{'class':'price_color'})
stocks = soup.find_all('p',{'class':'instock availability'})

title_list=[title.text for title in titles if title.text]
price_list=[price.text for price in prices if price.text]
stock_list=[stock.text.replace('\n','').strip() for stock in stocks if stock.text]

dict={'Titles':title_list,'Prices':price_list, 'Stocks':stock_list}
df=pd.DataFrame(dict).set_index('Titles')

df

200

                                       Prices    Stocks
Titles
A Light in the ...                     £51.77  In stock
Tipping the Velvet                     £53.74  In stock
Soumission                             £50.10  In stock
Sharp Objects                          £47.82  In stock
Sapiens: A Brief History ...           £54.23  In stock
The Requiem Red                        £22.65  In stock
The Dirty Little Secrets ...           £33.34  In stock
The Coming Woman: A ...                £17.93  In stock
The Boys in the ...                    £22.60  In stock
The Black Maria                        £52.15  In stock
Starving Hearts (Triangular Trade ...  £13.99  In stock
Shakespeare's Sonnets                  £20.66  In stock
Set Me Free                            £17.46  In stock
Scott Pilgrim's Precious Little ...    £52.29  In stock
Rip it Up and ...                      £35.02  In stock
Our Band Could Be ...                  £57.25  In stock
Olio                                   £23.88  In stock
Mesaerion: The Best Science ...        £37.59  In stock
Libertarianism for Beginners           £51.33  In stock
It's Only the Himalayas                £45.17  In stock